import json

Neighbourhood_158 = [
  "Agincourt North (129)",
  "Agincourt South-Malvern West (128)",
  "Alderwood (20)",
  "Annex (95)",
  "Avondale (153)",
  "Banbury-Don Mills (42)",
  "Bathurst Manor (34)",
  "Bay–Cloverhill (169)",
  "Bayview Village (52)",
  "Bayview Woods-Steeles (49)",
  "Bedford Park-Nortown (39)",
  "Beechborough-Greenbrook (112)",
  "Bendale–Glen Andrew (156)",
  "Bendale South (157)",
  "Birchcliffe-Cliffside (122)",
  "Black Creek (24)",
  "Blake-Jones (69)",
  "Briar Hill-Belgravia (108)",
  "Bridle Path-Sunnybrook-York Mills (41)",
  "Broadview North (57)",
  "Brookhaven-Amesbury (30)",
  "Cabbagetown-South St. James Town (71)",
  "Caledonia-Fairbank (109)",
  "Casa Loma (96)",
  "Centennial Scarborough (133)",
  "Church–Wellesley (167)",
  "Clairlea-Birchmount (120)",
  "Clanton Park (33)",
  "Cliffcrest (123)",
  "Corso Italia-Davenport (92)",
  "Danforth - East York (59)",
  "Danforth (66)",
  "Don Valley Village (47)",
  "Dorset Park (126)",
  "Downtown Yonge East (168)",
  "Dovercourt Village (172)",
  "Downsview (155)",
  "Dufferin Grove (83)",
  "East End-Danforth (62)",
  "East L'Amoreaux (148)",
  "Edenbridge-Humber Valley (9)",
  "Eglinton East (138)",
  "Elms-Old Rexdale (5)",
  "Englemount-Lawrence (32)",
  "Eringate-Centennial-West Deane (11)",
  "Etobicoke City Centre (159)",
  "Etobicoke West Mall (13)",
  "Fenside-Parkwoods (150)",
  "Flemingdon Park (44)",
  "Forest Hill North (102)",
  "Forest Hill South (101)",
  "Fort York–Liberty Village (163)",
  "Glenfield-Jane Heights (25)",
  "Golfdale-Cedarbrae-Woburn (141)",
  "Greenwood-Coxwell (65)",
  "Guildwood (140)",
  "Harbourfront-CityPlace (165)",
  "Henry Farm (53)",
  "High Park North (88)",
  "High Park-Swansea (87)",
  "Highland Creek (134)",
  "Hillcrest Village (48)",
  "Humber Bay Shores (161)",
  "Humber Heights-Westmount (8)",
  "Humber Summit (21)",
  "Humbermede (22)",
  "Humewood-Cedarvale (106)",
  "Ionview (125)",
  "Islington (158)",
  "Junction Area (90)",
  "Junction–Wallace Emerson (171)",
  "Keelesdale-Eglinton West (110)",
  "Kennedy Park (124)",
  "Kensington-Chinatown (78)",
  "Kingsview Village-The Westway (6)",
  "Kingsway South (15)",
  "L'Amoreaux West (147)",
  "Lambton Baby Point (114)",
  "Lansing-Westgate (38)",
  "Lawrence Park North (105)",
  "Lawrence Park South (103)",
  "Leaside-Bennington (56)",
  "Little Portugal (84)",
  "Long Branch (19)",
  "Malvern East (146)",
  "Malvern West (145)",
  "Maple Leaf (29)",
  "Markland Wood (12)",
  "Milliken (130)",
  "Mimico-Queensway (160)",
  "Morningside (135)",
  "Morningside Heights (144)",
  "Moss Park (73)",
  "Mount Dennis (115)",
  "Mount Olive-Silverstone-Jamestown (2)",
  "Mount Pleasant East (99)",
  "New Toronto (18)",
  "Newtonbrook East (50)",
  "Newtonbrook West (36)",
  "North Riverdale (68)",
  "North St. James Town (74)",
  "North Toronto (173)",
  "O'Connor-Parkview (54)",
  "Oakdale–Beverly Heights (154)",
  "Oakridge (121)",
  "Oakwood Village (107)",
  "Old East York (58)",
  "Palmerston-Little Italy (80)",
  "Parkwoods-O'Connor Hills (149)",
  "Pelmo Park-Humberlea (23)",
  "Playter Estates-Danforth (67)",
  "Pleasant View (46)",
  "Princess-Rosethorn (10)",
  "Regent Park (72)",
  "Rexdale-Kipling (4)",
  "Rockcliffe-Smythe (111)",
  "Roncesvalles (86)",
  "Rosedale-Moore Park (98)",
  "Rouge (131)",
  "Runnymede-Bloor West Village (89)",
  "Rustic (28)",
  "Scarborough Village (139)",
  "South Eglinton–Davisville (174)",
  "South Parkdale (85)",
  "South Riverdale (70)",
  "St. Andrew-Windfields (40)",
  "St Lawrence-East Bayfront-The Islands (166)",
  "Steeles (116)",
  "Stonegate-Queensway (16)",
  "Tam O'Shanter-Sullivan (118)",
  "Taylor Massey (61)",
  "The Beaches (63)",
  "Thistletown-Beaumond Heights (3)",
  "Thorncliffe Park (55)",
  "Trinity-Bellwoods (81)",
  "University (79)",
  "Victoria Village (43)",
  "Wellington Place (164)",
  "West Hill (136)",
  "West Humber-Clairville (1)",
  "West Queen West (162)",
  "West Rouge (143)",
  "Westminster-Branson (35)",
  "Weston (113)",
  "Weston-Pelham Park (91)",
  "Wexford-Maryvale (119)",
  "Willowdale East (152)",
  "Willowdale West (37)",
  "Willowridge-Martingrove-Richview (7)",
  "Woburn North (142)",
  "Woodbine Corridor (64)",
  "Woodbine-Lumsden (60)",
  "Wychwood (94)",
  "Yonge–Bay Corridor (170)",
  "Yonge-Eglinton (100)",
  "Yonge–Doris (151)",
  "Yonge-St. Clair (97)",
  "York University Heights (27)",
  "Yorkdale-Glen Park (31)"
] 
Primary_Offence = ["Wilful Promotion of Hatred", "Assault With a Weapon", "Mischief Under $5000", "Indecent Communications", "Assault", "Uttering Threats - Bodily Harm", "Criminal Harassment", "Mischief Interfere With Property", "Mischief To Religious Property, Educational Institutions, Etc.", 
                   "Assault Causing Bodily Harm", "Uttering Threats - Property", "Public Incitement of Hatred ", "Arson",
                   "Theft","Robbery", "Disturbing Religious Worship Or Certain Meetings",
                   "Causing a Disturbance", "Advocating Genocide", "Firearms Related Offence",
                   "Harassing Communications", "Mischief Over $5000", "Mischief To Data",
                   "Assault Peace Officer","Other Criminal Code Offence Not Listed","Sexual Assault",
                   "Murder","Dangerous Operation Motor Vehicle", "Fail To Comply Probation", "Aggravated Assault"]
Division = ["D33", "D42", "D53", "D52", "D32", "D13", "D14", "D12", "D31", "D51",
"D43", "D22", "D55", "D11", "D41", "D23"]
Location_type = ["Religious Place of Worship/Cultural Centre","House (Townhouse, Retirement Home, Garage, Vehicle, Cottage)",
                 "Educational Institution (Universities, Colleges, Schools, etc.)",
                 "Streets/Roadways/Highway",
                 "Business/Retail",
                 "Other Commercial / Corporate Places ",
                 "Public Transportation",
                 "Government Building (Courthouse, Museums, Parliament Building, etc.)",
                 "Apartment Building (Condo, Retirement Buidling, etc.)",
                 "Open Area, Park or Parking Lot",
                 "Government Building",
                 "Medical Facility (Hospitals, Long-term Care, etc.)",
                 "Non-Commercial/Non for Profit"   ]

with open("Neighbourhood_158.json", "w") as f:
    json.dump(Neighbourhood_158, f, indent=2)

with open("Primary_Offence.json", "w") as f:
    json.dump(Primary_Offence, f, indent=2)

with open("Division.json", "w") as f:
    json.dump(Division, f, indent=2)

with open("Location_type.json", "w") as f:
    json.dump(Location_type, f, indent=2)
